### PR TITLE
Create AYSH

### PR DESCRIPTION
**Pull request by ayeshapatellll**
PLEASE HELP TO WRITE A PSEUDOCODE FOR THIS CODE

### CODE REVIEW

**Comment by AbhiTaker** [comment]
Hi @ayeshapatellll 

First of all, the code needs to be written in a standard form to get converted in pseudo code by this application and this code can only convert C++ programs, so printf( ) and scanf( ) won't work. Still there are many standard features that we haven't implemented in this application.

Do you want a pseudo code of only your above code?

**Comment by ayeshapatellll** [comment]
yes

**Comment by AbhiTaker** [comment]
You want a pseudo-code explicitly for this program?

**Comment by ayeshapatellll** [comment]
Yes please

AYESHA PATEL

________________________________

**Comment by AbhiTaker** [comment]
http://www.unf.edu/~broggio/cop2221/2221pseu.htm

**Pull request closed without merging**
